ERROR 2025-05-20 10:35:48,037 log 26448 128761621108416 Internal Server Error: /
Traceback (most recent call last):
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/core/views.py", line 22, in home
    return render(request, 'core/home.html', {'latest_posts': latest_posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 45: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2025-05-20 10:35:48,038 basehttp 26448 128761621108416 "GET / HTTP/1.1" 500 188595
ERROR 2025-05-20 10:36:55,462 log 26448 128761621108416 Internal Server Error: /
Traceback (most recent call last):
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/core/views.py", line 22, in home
    return render(request, 'core/home.html', {'latest_posts': latest_posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 45: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2025-05-20 10:36:55,463 basehttp 26448 128761621108416 "GET / HTTP/1.1" 500 188595
ERROR 2025-05-20 10:37:01,763 log 26448 128761630549696 Internal Server Error: /
Traceback (most recent call last):
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/core/views.py", line 22, in home
    return render(request, 'core/home.html', {'latest_posts': latest_posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 45: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2025-05-20 10:37:01,764 basehttp 26448 128761630549696 "GET / HTTP/1.1" 500 188458
ERROR 2025-05-20 10:37:24,800 log 26448 128761621108416 Internal Server Error: /
Traceback (most recent call last):
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/core/views.py", line 22, in home
    return render(request, 'core/home.html', {'latest_posts': latest_posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/aditya/Desktop/multibpreneur_website/venv/lib/python3.12/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 45: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR 2025-05-20 10:37:24,801 basehttp 26448 128761621108416 "GET / HTTP/1.1" 500 188618
ERROR 2025-06-08 07:30:48,464 basehttp 21796 130135722292928 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:30:53,020 basehttp 21796 130135722292928 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:30:55,898 basehttp 21796 130135722292928 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:30:56,995 basehttp 21796 130135722292928 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:30:58,078 basehttp 21796 130135722292928 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:31:04,301 basehttp 21796 130135722292928 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:31:08,494 basehttp 21796 130135722292928 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:31:17,821 basehttp 21796 130135722292928 "GET /admin/ HTTP/1.1" 500 59
ERROR 2025-06-08 07:31:17,908 basehttp 21796 130135722292928 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:31:25,185 basehttp 21796 130135722292928 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:13,225 basehttp 21796 130135713900224 "GET /admin HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:13,419 basehttp 21796 130135713900224 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:15,705 basehttp 21796 130135713900224 "GET /admin HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:15,735 basehttp 21796 130135713900224 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:16,638 basehttp 21796 130135713900224 "GET /admin HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:16,660 basehttp 21796 130135713900224 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:21,055 basehttp 21796 130135722292928 "GET /admin HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:21,259 basehttp 21796 130135722292928 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:25,678 basehttp 21796 130135713900224 "GET /admin/ HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:25,715 basehttp 21796 130135713900224 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:31,609 basehttp 21796 130135713900224 "GET /admin/auth/user/ HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:31,644 basehttp 21796 130135713900224 "GET /favicon.ico HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:50,097 basehttp 21796 130135722292928 "GET /admin HTTP/1.1" 500 59
ERROR 2025-06-08 07:34:50,308 basehttp 21796 130135722292928 "GET /favicon.ico HTTP/1.1" 500 59
